spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/devblog
    driverClassName: org.mariadb.jdbc.Driver
    username: blog
    password: blog

  jpa:
    hibernate:
      ddl-auto: create
      # create: 기존테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      # create-drop: create와 같으나 종료 시점에 테이블 DROP
      # none: 사용하지 않음
    generate-ddl: false # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    show-sql: true  # 실행되는 쿼리문 보여주기 여부
    database: mysql # 사용되는 데이터베이스(MariaDB는 없기 때문에 mysql로 지정)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect